version: '3'
services:
  api:
    container_name: auth_api_service
    build:
      context: app
      dockerfile: settings/docker/fastapi/dockerfile
    ports:
      - "8000:8000"
    env_file:
      app/.env
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 10s
    depends_on:
      - redis
      - postgres
      
  redis:
    container_name: auth_redis_cache
    build:
      context: app
      dockerfile: settings/docker/redis/dockerfile
    env_file:
      app/.env
    ports:
      - "6379"


  postgres:
    container_name: auth_postgres
    build:
      context: app/settings/docker/postgres
      dockerfile: dockerfile
    env_file:
      app/.env
    ports:
      - "5432"

networks:
  default:
      name: auth_network