FROM python:3.10

WORKDIR /opt/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH /opt/app


RUN python -m venv /opt/.venv
# Enable venv
ENV PATH="/opt/.venv/bin:$PATH"

COPY requirements.txt requirements.txt

RUN apt-get update && \
    apt-get install -y netcat-traditional

RUN  pip install --upgrade pip \
     && pip install -r requirements.txt --no-cache-dir

COPY ./settings/docker/fastapi/*.sh .

COPY src src
COPY alembic alembic
COPY alembic.ini alembic.ini

ENTRYPOINT ["/bin/bash", "./run_gunicorn.sh"]
